# Generated by Django 5.1 on 2024-08-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
